### ISSUE TITLE
when the code will be released？

### ISSUE THREAD

**Issue by Grassyue** [Zi-YuanYang/HyperFed#1]
Thank you for your sharing. It is an interesting work!
When the code will be released？

**Comment by Zi-YuanYang** [comment]
@Grassyue Thx for your attention, we are so happy you enjoy this work! This paper is not submitted yet, the codes will be released immediately when this paper is accepted. We wish we can release codes in the near future, thx for your attention again.

**Comment by parmahadi** [comment]
I'm interesting with your work when the code will be released?

**Comment by Zi-YuanYang** [comment]
We're happy that you are interested in our work, and this paper has been accepted today. We will release the codes in the coming days. @parmahadi

**Comment by Zi-YuanYang** [comment]
We've released our codes, thanks for your interest again. @Grassyue @parmahadi
